language: node_js
cache: npm

script: npm run lint

before_deploy:
  - npm run build
  - touch out/.nojekyll

deploy:
  provider: pages
  local_dir: out
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
